# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory=$(omarchy-cmd-terminal-cwd)
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER, D, Docker, exec, omarchy-launch-tui lazydocker

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
unbind = SUPER, W
bindd = SUPER, Q, Close active window, killactive,

unbind = SUPER, E
bindd = SUPER, E, File manager, exec, uwsm app -- nautilus --new-window


unbind = SUPER, T
bindd = SUPER, T, Todoist quick add, exec, /home/adam/.local/bin/test

bindd = SUPER, U, inkscape styler, exec, /home/adam/.local/bin/inkscape-styler

##############################
###   KEYBOARD AS A MOUSE  ###
##############################
bind = SUPER, comma, submap, mousemove
submap = mousemove
binde = , left, exec, ydotool mousemove -- -40 0 && sleep 0.1
binde = , right, exec, ydotool mousemove -- 40 0 && sleep 0.1 
binde = , up, exec, ydotool mousemove -- 0 -40 && sleep 0.1 
binde = , down, exec, ydotool mousemove -- 0 40 && sleep 0.1

# mouse clicks
bind = , return, exec, ydotool click C0 #left
bind = shift, return, exec, ydotool click 0x40 #left hold
bind = ctrl, return, exec, ydotool click 0x41 0x81 # right
#bind = , return, exec, ydotool click 0x42 0x82 #middle

# diagonal movements
#binde = shift, left, exec, ydotool mousemove -- -28 -28 && sleep 0.1  # Up-Left
#binde = shift, right, exec, ydotool mousemove -- 28 -28 && sleep 0.1  # Up-Right
#binde = ctrl, left, exec, ydotool mousemove -- -28 28 && sleep 0.1  # Down-Left
#binde = ctrl, right, exec, ydotool mousemove -- 28 28 && sleep 0.1 

#fine control movements
binde = ctrl, left, exec, ydotool mousemove -- -10 0 && sleep 0.1
binde = ctrl, right, exec, ydotool mousemove -- 10 0 && sleep 0.1 
binde = ctrl, up, exec, ydotool mousemove -- 0 -10 && sleep 0.1 
binde = ctrl, down, exec, ydotool mousemove -- 0 10 && sleep 0.1

#reset submap
bind = SUPER, comma, submap, reset
submap = reset
