#!/usr/bin/env bash


# Check if a file name is provided
if [ -z "$1" ]; then
  echo "Error: A file name must be set, e.g. \"the wonderful thing about tiggers\"."
  exit 1
fi

formatted_file_name="${1}.md"
cd "/home/adam/notes" || exit
touch "Inbox/${formatted_file_name}"
nvim "Inbox/${formatted_file_name}"

