import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15